package br.com.meiadois.decole.presentation.user.account.binding

enum class FieldsEnum {
    COMPANY_NAME,
    COMPANY_CEP,
    COMPANY_THUMBNAIL,
    COMPANY_BANNER,
    COMPANY_CNPJ,
    COMPANY_CELLPHONE,
    COMPANY_EMAIL,
    COMPANY_DESCRIPTION,
    COMPANY_VISIBLE,
    COMPANY_CITY,
    COMPANY_NEIGHBORHOOD,
    COMPANY_SEGMENT,

    USER_NAME,
    USER_EMAIL,
    USER_NEWPASSWORD,
    USER_CONFIRMPASSWORD,
    USER_CURRENTPASSWORD
}